### ISSUE TITLE
Python 3.4, Win 64 Failure

### ISSUE THREAD

**Issue by scopatz** [conda-forge/staged-recipes#448] opened 2016-04-22 20:33 UTC
There are a couple of unrelated issues that have come up with non-nonsensical failures on the titular platform when no other platforms fail. In particular, these are #395 and conda-forge/xonsh-feedstock#7.

@pelson @melund @ocefpaf @jakirkham @msarahan @patricksnape

**Comment by jakirkham** [comment] 2016-04-22 20:37
These appear to have arisen after the conda-build 1.20.1 release so am curious if this might be a bug in there or if something we are doing here is confusing it.

**Comment by melund** [comment] 2016-04-23 06:46
Downgrading`conda-build` to 1.20.0 is a workaround for now. https://github.com/conda-forge/xonsh-feedstock/pull/7#

**Comment by patricksnape** [comment] 2016-04-23 11:41
Oh no, looks like I broke something :(. I will investigate as soon as I get back in. Sorry guys!

**Comment by pelson** [comment] 2016-04-25 10:01
A workaround has been proposed in conda-smithy https://github.com/conda-forge/conda-smithy/pull/143. We will either have to pin for now, or wait for a new conda-build release. Ping @kalefranz - are you likely to be able to issue a minor release of conda-build in the next 5 days, or should we plan to workaround the issue (i.e. pin the version back) for a little while?

**Comment by ocefpaf** [comment] 2016-04-25 10:03
> Ping @kalefranz - are you likely to be able to issue a minor release of conda-build in the next 5 days, or should we plan to workaround the issue (i.e. pin the version back) for a little while?

I guess that 5 days can be too much for the activity here. Maybe we should pin to `1.20.0`. I can do that in a moment...

**Comment by jakirkham** [comment] 2016-04-25 22:56
> Oh no, looks like I broke something :(. I will investigate as soon as I get back in. Sorry guys!

Thanks for looking into @patricksnape. Please let us know if you have something.

FWIW, it seems like we can't use 1.20.1 for several reasons right now. This is just one of them.

**Comment by jakirkham** [comment] 2016-04-25 23:05
> are you likely to be able to issue a minor release of conda-build in the next 5 days, or should we plan to workaround the issue (i.e. pin the version back) for a little while?

Is there actually a fix for this problem? I have been out for several days so may have missed it. Though I don't think Windows is fixed for this case yet.

**Comment by jakirkham** [comment] 2016-04-26 00:14
I'm bumping this upstream ( https://github.com/conda/conda-build/issues/895 ).

**Comment by jakirkham** [comment] 2016-04-26 00:18
Also, there seems to be some confusion that only has become clear to me after reading more of my backlogged notifications. There are two issues that require a rollback.

1. This issue on Mac/Travis ( https://github.com/conda/conda-build/issues/889 ).
2. A build issue on Windows with Python 3.4 and 64-bit ( https://github.com/conda/conda-build/issues/895 ).

There is an accepted fix for 1 ( https://github.com/conda/conda-build/pull/892 ), which we should test somehow to make sure it really fixes our problems. There is no fix for 2 AFAICT.

**Comment by jakirkham** [comment] 2016-04-26 01:16
Proposed fix for conda-smithy ( https://github.com/conda-forge/conda-smithy/pull/145 ).

**Comment by jakirkham** [comment] 2016-04-26 01:21
Tweak to the staged-recipe fix ( https://github.com/conda-forge/staged-recipes/pull/455 ).

**Comment by jakirkham** [comment] 2016-04-26 19:42
These proposed workarounds are already in place at this point. The issue is fundamentally a `conda-build` issue and has been placed here ( https://github.com/conda/conda-build/issues/895 ). Please track that issue for progress. This will be closed as there is nothing still actionable here. If you feel otherwise, please explain what it is you would like to see changed and why it is in the conda-forge domain.

**Closed by jakirkham** 2016-04-26 19:42 UTC
