### ISSUE TITLE
Recipes in staged-recipes not converting

### ISSUE THREAD

**Issue by hameerabbasi** [conda-forge/staged-recipes#5660] opened 2018-04-16 16:04 UTC
As title.

**Comment by jakirkham** [comment] 2018-04-16 19:41
This is a known issue.

We are in progress of migrating between `conda-build` 2 and `conda-build` 3 since last week (hoping to complete soon). The migration has `staged-recipes` in a broken state currently. We are currently discussing the best way to proceed.

Have updated the title to more generally reflect the issue at hand as it is not specific to `sparse`.

**Comment by hameerabbasi** [comment] 2018-04-18 07:16
[It seems the `master` build is still erroring out.](https://travis-ci.org/conda-forge/staged-recipes/builds/367840351)

**Comment by jakirkham** [comment] 2018-04-18 07:49
Yep, this is filed already as issue ( https://github.com/conda-forge/conda-smithy/issues/742 ). A proposal is coming together for a fix.

**Comment by jakirkham** [comment] 2018-04-18 16:30
`conda-smithy` 3.1.0 was released earlier today, which includes a fix for the aforementioned issue. Feedstock conversion is proceeding (albeit slowly). Will update when it is complete.

**Comment by jakirkham** [comment] 2018-04-18 16:59
~30 recipes were pending conversion we have cut this down to ~1/3 waiting for conversion. However we are now encountering a GitHub rate limiting issue with AppVeyor, which will block things for a little while (hopefully no longer than 1hr). So will retry after that time has elapsed.

**Comment by carlodri** [comment] 2018-04-18 18:18
thanks @jakirkham and all @conda-forge/core for all your time and dedication to the development of this great tool!

**Comment by jakirkham** [comment] 2018-04-18 19:11
Honestly @isuruf, @scopatz, @msarahan, @ocefpaf, and probably many more all deserve shout outs for quick fixes in `conda-smithy`, speeding up the release process, and generally helping advise/review.

**Comment by jakirkham** [comment] 2018-04-18 19:17
All of the original recipes that were backlogged have converted. CIs are currently running to build all of those packages. It will probably take a bit for them to catch up. Should issues occur in the feedstocks please raise on the respective feedstock and ping `core`.

Of course there are things being merged even now. So this will never be done per se, but things appear to be up and running as intended again.

Thanks to everyone that helped out. Also thanks to the community for their patience as we navigated these issues.

**Closed by jakirkham** 2018-04-18 19:17 UTC
Labels: maintenance

**Comment by bgruening** [comment] 2018-04-18 21:24
Thanks all!
