### ISSUE TITLE
Travis CI ValueError: max() arg is an empty sequence

### ISSUE THREAD

**Issue by frol** [conda-forge/staged-recipes#2498] opened 2017-02-25 08:37 UTC
It took Travis CI 3 days to get my PR #2479 running to only get to the point where it crashed:

```
Checking to see if this PR build is outdated.
Traceback (most recent call last):
  File "<stdin>", line 192, in <module>
  File "<stdin>", line 181, in main
  File "<stdin>", line 93, in travis_check_latest_pr_build
ValueError: max() arg is an empty sequence
```

https://travis-ci.org/conda-forge/staged-recipes/builds/204311587

**Comment by jakirkham** [comment] 2017-02-25 22:56
Duplicate of issue ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/issues/57 ). Fixed in PR ( https://github.com/conda-forge/conda-forge-build-setup-feedstock/pull/59 ).

**Closed by jakirkham** 2017-02-25 22:56 UTC
