### ISSUE TITLE
rpy2 update needed

### ISSUE THREAD

**Issue by huidongchen** [conda-forge/staged-recipes#8205] opened 2019-04-24 14:07 UTC
Hi,

The rpy2 version in conda-forge is a bit behind. It's causing some errors in our bioconda recipe 'stream'. It seems either a missing dependency in conda, or mismatching dependencies between conda's R and rpy2.

Currently we are unable to update the bioconda package 'stream'.
https://github.com/bioconda/bioconda-recipes/pull/14549
https://github.com/bioconda/bioconda-recipes/issues/14550

I would appreciate your help. Thanks!

**Comment by isuruf** [comment] 2019-04-24 21:52
Duplicate of https://github.com/conda-forge/rpy2-feedstock/issues/20

**Closed by isuruf** 2019-04-24 21:52 UTC
