### ISSUE TITLE
r-sqldf in conflict with other packages

### ISSUE THREAD

**Issue by lagerratrobe** [conda-forge/staged-recipes#4854] opened 2018-01-27 22:47 UTC
Been trying to install r-sqldf and have had no joy.  Keep getting errors like this:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - r-rjdbc
  - r-sqldf
```
I tried removing r-rjdbc and then it generates another conflict message:
```
The following packages will be REMOVED:

    r-rjdbc: 0.2_5-r342he0388cf_0 r
    rstudio: 1.1.383-h2c9cdda_2   r

Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

$ sudo conda install -c conda-forge r-sqldf
Solving environment: failed

UnsatisfiableError: The following specifications were found to be in conflict:
  - r-pki
  - r-sqldf
Use "conda info <package>" to see the dependencies for each package.
```
Etc, etc ad nauseum.

Any thoughts about how I can get around this?

**Comment by dougalsutherland** [comment] 2018-01-28 22:58
The easiest thing to do, if it works for you, is to make a new [conda environment] for it: `conda create -n tmp r-sqldf`. That will definitely let you install `r-sqldf`.

It seems the problem is that `conda-forge`'s R packages are built only for R versions 3.4.1 and 3.3.2, but Anaconda Inc is building R packages (or at least `r-rjdbc`) only for R 3.4.2. (You can find this out with `conda info`, as suggested, but it's not super obvious.)

Apparently this was decided in https://github.com/conda-forge/r-base-feedstock/pull/27#issuecomment-351115809 by @bgruening / @ocefpaf. Kind of unfortunately, this probably means that if you need to use both at the same time, you might have to do one of:
-  add (or request someone to add) `r-rjdbc` to `conda-forge`
- convince the powers that be to upgrade to R 3.4.2, and wait a while for all of the CI builds to go through (particularly on Mac)
- hack [the `conda-forge` `r-sqldf` recipe](https://github.com/conda-forge/r-sqldf-feedstock), and potentially all of its dependencies, to build against R 3.4.2 for yourself
- just install one or the other in your environment without using `conda`.

**Comment by ocefpaf** [comment] 2018-01-28 23:03
@dougalsutherland I'm OK re-building our R stack for 3.4.2 but that will take tons of CI resources and I am not sure we can afford that at the moment.

**Comment by bgruening** [comment] 2018-01-28 23:05
Adding r-rjdbc to conda-forge is probably the easiest and right thing to do here. The R packages from default and conda-forge are not compatible afaik and already caused a lot of pain.

Building against R 3.4.2 is ok, but it takes so many resources. I'm unsure if its worth it. Including Bioconda this means >1000 packages.

**Comment by dougalsutherland** [comment] 2018-01-28 23:07
Yeah, if `r-rjdbc` is easy to package then that's definitely the best short-term option, especially given the Travis situation.

**Comment by randre69** [comment] 2018-01-31 21:12
Thanks for the suggestions.  I can try the temp environment, but wouldn't I end up having a conflict with something else pretty quickly?  I tried removing r-rjdbc, then r-pki and it felt like I was in a dependency loop.  I'd remove the one that conflicted and get another the very next time I tried to install r-sqldf.

Would it be possible for me to compile/build r-sqldf locally to work with my Anaconda distro?

**Comment by dougalsutherland** [comment] 2018-02-01 15:29
I think with R you currently need to either go all conda-forge or all defaults, so the temp environment wouldn't help you if need `r-rjdbc`. Not sure about others. If you make a list of packages you need and request them to be added to conda-forge, maybe someone will do it, or you can do it yourself. :)

To work with `defaults`, you could try cloning https://github.com/conda-forge/r-sqldf-feedstock and running `conda build recipe`; that will probably work.

**Comment by lagerratrobe** [comment] 2018-02-01 15:34
Ok, I think I'm going to just forego the use of sqldf in Jupyter for now.  I can accomplish what I need without it, it's just that a class I'm taking wants to use it.

Thanks again for the feedback.

**Comment by jdblischak** [comment] 2018-02-17 03:53
I looked into adding r-jdbc to conda-forge, but unfortunately we can't add it at the moment. It depends on r-rjava, which we can't get to build with R 3.4.1.

https://github.com/conda-forge/r-rjava-feedstock/pull/1

And there's really no reason to build packages for R 3.4.2 or 3.4.3 at this point. R 3.5.1 will be here before we know it.

**Comment by jakirkham** [comment] 2020-09-28 18:55
We have since migrated through a few R versions (include 4.0). Given this, am going to go ahead and close this out. If there are new issues, please feel free to raise them in new issues. Thanks!

**Closed by jakirkham** 2020-09-28 18:55 UTC
