### ISSUE TITLE
move to CircleCI

### ISSUE THREAD

**Issue by beckermr** [conda-forge/staged-recipes#10686] opened 2020-01-25 09:00 UTC
Right now we are hitting our API rate limit a lot. Further, the autorebuild trigger is not always working. Travis sat idle for 3 hours overnight. 

I think maybe we should move to a travis cron job that runs once an hour until we can come up with a better fix. This will concert as many recipes as we can given the current constraints. 

@conda-forge/staged-recipes @conda-forge/core @jakirkham for viz

**Comment by beckermr** [comment] 2020-01-25 09:00
If we did this we should turn off builds on pushes to master.

**Comment by jakirkham** [comment] 2020-01-25 12:17
So we already have a cron job. Unfortunately Travis CI doesn’t allow anything more frequent than daily. It would be nice to have hourly builds, but am not seeing anything simple to solve this. Suggestions welcome

I remain suspicious that Drone syncs are the cause of the rate limit exhaustion ( https://github.com/conda-forge/conda-smithy/issues/1221 ). This also matches my personal experience using their UI for syncing. Briefly looked over their API, but didn’t see any clear alternatives. Though maybe others have good ideas here

**Comment by beckermr** [comment] 2020-01-25 12:40
CircleCI has hourly builds. Can we run the scripts there?

**Comment by beckermr** [comment] 2020-01-25 12:45
We could also build one recipe only, examine the time it takes until it resets, sleep for that time, and then trigger the build again.

**Comment by jakirkham** [comment] 2020-01-25 13:03
If we move CIs, it seems worth considering Azure as we already use that for everything else. Idk what they offer in terms of cron jobs though.

**Comment by beckermr** [comment] 2020-01-25 13:11
For sure! I didn't want to deal with having more than one config per provider. I also think the azure logging is not very good. However, they do support cron syntax: https://mohitgoyal.co/2019/07/02/schedule-azure-devops-pipelines-using-cron-syntax/

**Comment by beckermr** [comment] 2020-01-25 13:17
Also, we should swap the loop ordering so we build one recipe from start to finish in topological order of any dependencies.

**Comment by beckermr** [comment] 2020-01-25 13:31
It appears that when we are out of API requests, we never make it to the point where we retrigger the build. We should make the job sleep and then exit with status 1.

**Comment by beckermr** [comment] 2020-01-25 13:41
let's try this  one :

**Comment by beckermr** [comment] 2020-01-25 13:42
https://github.com/conda-forge/staged-recipes/pull/10688

**Comment by beckermr** [comment] 2020-01-25 15:03
Well that didn’t do it...

**Comment by beckermr** [comment] 2020-01-25 15:16
I’m leaving this code on master. Feel free to remove it or change it if someone can figure out where I went wrong.

**Comment by beckermr** [comment] 2020-01-31 15:48
Alright, so the code I put on master to sleep did not help things and backed up the travis queue. 

A few things:

1. The actual issue here is that travis has API rate limits on how often we can trigger builds via the API. 
2. We cannot use a cron job IIUIC because we never want more than one job on master doing conversions. Cron jobs could overlap. Instead we need to trigger new jobs.
3. We can really only convert about 2 recipes an hour. 

So given all of this, I propose we move the conversion build to circleCI. My reasoning for choosing this over azure is as follows:

1. We currently don't build many if any actual feedstocks on circleCI. We certainly if we do, they are OSX and not linux. Thus we have free capacity there.
2. Moving this to CircleCI would make maintenance of the azure scripts on staged-recipes simpler. We simply have circleCI trigger only on master and only do conversions. 
3. Freeing up travis will help us potentially test recipes on ppc64le as they come in.
4. CircleCI has a nice API for triggering builds on master without a lot of fuss.
5. By using circle, we can turn the sleep I put in back on and so have the jobs wait automatically for more github api requests. We can also setup staged recipes to only convert one feedstock per job which will move things out nicely.

Thoughts @conda-forge/core @conda-forge/staged-recipes ?

**Comment by isuruf** [comment] 2020-01-31 16:27
I think we are trying to fix side-effects of one root problem that we are not trying to fix.
Root issue that we can only create one feedstock per hour is that we are using the token for the same bot user for Travis and Drone. If we switched the drone token to a new user, all these problems go away.

**Comment by beckermr** [comment] 2020-01-31 16:28
Ahhhh ok. Can you do that then? We are basically backed up all the time at this point.

**Comment by isuruf** [comment] 2020-01-31 16:29
> Can you do that then? 

Nope. I can't make github accounts anymore as I get flagged by Github. @ocefpaf tried creating https://github.com/conda-forge-drone-ci-bot which didn't work I think

**Comment by isuruf** [comment] 2020-01-31 16:33
@ocefpaf, can you try registering on drone CI again with that bot? I think you weren't flagged by Github, but you got flagged by Drone CI right?

**Comment by ocefpaf** [comment] 2020-01-31 16:33
> @ocefpaf tried creating https://github.com/conda-forge-drone-ci-bot which didn't work I think

Yep. They flagged the account name and as a bot :-)

I'll try again and ask nicely, again. I'll report back soon.

**Comment by isuruf** [comment] 2020-01-31 16:37
If someone has a bot account that can register on drone-ci (i.e. not a new account and has some activity) and willing to give it to conda-forge, that'll fix all these issues.

**Comment by beckermr** [comment] 2020-01-31 16:38
Well, it did have "bot" in the name. :)

Honestly, moving to circleci seems easier than all of these accounts. I'm ok converting one recipe per hour, I just want it to be reliable. As soon as we need more API keys for requests for some other service, we are going to hit this problem again. Running out of requests is fine, as long as we can reliable restart, and that is where travis is falling down. 

However, I'll hold off on pushing for circleCI until we exhaust getting a new bot or we make that work. LMK!

**Comment by marcelotrevisani** [comment] 2020-01-31 16:42
Did you try with git hub actions?

**Comment by beckermr** [comment] 2020-01-31 16:43
I am trying to reserve actions capacity for the autotick bot infrastructure. CircleCI is relatively unused by conda-forge right now.

**Comment by beckermr** [comment] 2020-01-31 18:46
It appears we are out right now. One of us should kick travis in about 15 minutes.

**Comment by beckermr** [comment] 2020-01-31 19:12
The latest job had a bunch of drone registration failures and then ran out of travis rebuild requests.

**Comment by beckermr** [comment] 2020-01-31 19:12
Drone still appears to be draining a bunch of API requests from the status printout. Is that status not for the main key but only for the drone key?

**Comment by beckermr** [comment] 2020-01-31 19:14
Ohhhh it is printing for both keys. We will have to change that.

**Comment by isuruf** [comment] 2020-01-31 19:18
Let's try again in an hour.

**Comment by beckermr** [comment] 2020-01-31 19:28
k - i;m gonna queue up a PR to make the monitoring a little better

**Comment by beckermr** [comment] 2020-01-31 21:14
So we converted three recipes this time and then hit the travis build API limit again. Weirdly, the drone sync call used maybe 100-200 API requests, but the feedstock registration drained a ton. 

I think I am confused about where the expensive calls are.

**Comment by beckermr** [comment] 2020-01-31 21:15
```GitHub API Rate Limit Info:
---------------------------
token:  GH_TOKEN
Currently remaining 0 out of 5000.
Will reset in 0:50:57.153850.
GitHub API Rate Limit Info:
---------------------------
token:  GH_DRONE_TOKEN
Currently remaining 4877 out of 5000.
Will reset in 0:47:15.885121.
```

**Comment by isuruf** [comment] 2020-01-31 21:16
Changing the drone token fixed one issue. This is another issue.

**Comment by beckermr** [comment] 2020-01-31 21:17
Right. So we either need to make the feedstock registration less expensive or we need to move to circleCI so we can bump the jobs more or switch to hourly cron jobs that convert 1-2 recipes at once.

**Comment by isuruf** [comment] 2020-02-03 01:53
This is fixed now I think. Changing the drone token fixed the most issues and the last obstacle was that the conversion failed at the step where webhooks were added and we switched to org wide webhooks which made it unnecessary.

**Comment by beckermr** [comment] 2020-02-03 02:27
Ok. Closing for now. Thanks for the good work @isuruf!

**Closed** 2020-02-03 02:27 UTC
